-- +goose Up
-- BASELINE for the `identity` schema — the squashed equivalent of migrations
-- 00001..00004, generated by pg_dump from those migrations rather than written
-- by hand (a hand-written baseline is precisely how a fresh database and an
-- already-migrated one drift apart).
--
-- WHY IT IS NUMBERED 00004 AND NOT 00001. goose applies any version above the
-- database's current max. Numbering the baseline at the CURRENT MAX means an
-- already-migrated cluster (staging is at 4) sees nothing to do, while a
-- fresh database applies this one file and lands on the SAME version number.
-- Both end up with identical schema AND identical ledger state. Numbering it
-- 00001 would instead leave fresh and existing clusters on different versions
-- forever.
--
-- CONSEQUENCE: this baseline may only ever be re-cut when every live
-- environment is at or above its version. Squashing below a deployed cluster's
-- version would make goose try to apply it over tables that already exist.
-- Verified before this was generated: staging was at exactly 00004.
--
-- The `goose_db_version` ledger is deliberately absent (goose creates it), as is
-- CREATE SCHEMA (infra owns schemas — charts/postgres/templates/cluster.yaml).
--
-- There is no Down. Baselines are not reversible: down-migrating past a squash
-- has no meaningful target, and the pre-squash steps no longer exist to unwind.

-- audit_log (TABLE)
CREATE TABLE identity.audit_log (
    id uuid NOT NULL,
    organization_id uuid,
    entity_type text NOT NULL,
    entity_id uuid NOT NULL,
    change_type text NOT NULL,
    actor_user_id uuid,
    occurred_at timestamp with time zone NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    changed_fields text[],
    change jsonb NOT NULL,
    CONSTRAINT audit_log_change_type_check CHECK ((change_type = ANY (ARRAY['create'::text, 'update'::text, 'delete'::text])))
);

-- users (TABLE)
CREATE TABLE identity.users (
    id uuid NOT NULL,
    oidc_sub text NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    email text DEFAULT ''::text NOT NULL,
    locale text DEFAULT 'en'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- audit_log audit_log_pkey (CONSTRAINT)
ALTER TABLE ONLY identity.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);

-- users users_keycloak_sub_key (CONSTRAINT)
ALTER TABLE ONLY identity.users
    ADD CONSTRAINT users_keycloak_sub_key UNIQUE (oidc_sub);

-- users users_pkey (CONSTRAINT)
ALTER TABLE ONLY identity.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- idx_audit_log_entity (INDEX)
CREATE INDEX idx_audit_log_entity ON identity.audit_log USING btree (entity_type, entity_id, recorded_at);

-- idx_users_email_lower (INDEX)
CREATE INDEX idx_users_email_lower ON identity.users USING btree (lower(email)) WHERE (email <> ''::text);


--
-- PostgreSQL database dump complete
--
