-- +goose Up
-- BASELINE for the `journeys` schema — the squashed equivalent of migrations
-- 00001..00003, generated by pg_dump from those migrations rather than written
-- by hand (a hand-written baseline is precisely how a fresh database and an
-- already-migrated one drift apart).
--
-- WHY IT IS NUMBERED 00003 AND NOT 00001. goose applies any version above the
-- database's current max. Numbering the baseline at the CURRENT MAX means an
-- already-migrated cluster (staging is at 3) sees nothing to do, while a
-- fresh database applies this one file and lands on the SAME version number.
-- Both end up with identical schema AND identical ledger state. Numbering it
-- 00001 would instead leave fresh and existing clusters on different versions
-- forever.
--
-- CONSEQUENCE: this baseline may only ever be re-cut when every live
-- environment is at or above its version. Squashing below a deployed cluster's
-- version would make goose try to apply it over tables that already exist.
-- Verified before this was generated: staging was at exactly 00003.
--
-- The `goose_db_version` ledger is deliberately absent (goose creates it), as is
-- CREATE SCHEMA (infra owns schemas — charts/postgres/templates/cluster.yaml).
--
-- There is no Down. Baselines are not reversible: down-migrating past a squash
-- has no meaningful target, and the pre-squash steps no longer exist to unwind.

-- audit_log (TABLE)
CREATE TABLE journeys.audit_log (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    entity_type text NOT NULL,
    entity_id uuid NOT NULL,
    change_type text NOT NULL,
    actor_user_id uuid,
    occurred_at timestamp with time zone NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    changed_fields text[],
    change jsonb NOT NULL,
    CONSTRAINT audit_log_change_type_check CHECK ((change_type = ANY (ARRAY['create'::text, 'update'::text, 'delete'::text])))
);

-- journey_plan_items (TABLE)
CREATE TABLE journeys.journey_plan_items (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    journey_id uuid NOT NULL,
    apiary_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);

-- journeys (TABLE)
CREATE TABLE journeys.journeys (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    name text NOT NULL,
    main_activity_type text NOT NULL,
    status text DEFAULT 'open'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    default_attributes jsonb,
    CONSTRAINT journeys_status_check CHECK ((status = ANY (ARRAY['open'::text, 'closed'::text])))
);

-- sync_conflict_log (TABLE)
CREATE TABLE journeys.sync_conflict_log (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    entity_type text NOT NULL,
    entity_id uuid NOT NULL,
    winning_payload jsonb NOT NULL,
    losing_payload jsonb NOT NULL,
    winner text NOT NULL,
    actor_user_id uuid,
    occurred_at timestamp with time zone,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT sync_conflict_log_winner_check CHECK ((winner = ANY (ARRAY['server'::text, 'client'::text])))
);

-- audit_log audit_log_pkey (CONSTRAINT)
ALTER TABLE ONLY journeys.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);

-- journey_plan_items journey_plan_items_pkey (CONSTRAINT)
ALTER TABLE ONLY journeys.journey_plan_items
    ADD CONSTRAINT journey_plan_items_pkey PRIMARY KEY (id);

-- journeys journeys_pkey (CONSTRAINT)
ALTER TABLE ONLY journeys.journeys
    ADD CONSTRAINT journeys_pkey PRIMARY KEY (id);

-- sync_conflict_log sync_conflict_log_pkey (CONSTRAINT)
ALTER TABLE ONLY journeys.sync_conflict_log
    ADD CONSTRAINT sync_conflict_log_pkey PRIMARY KEY (id);

-- idx_journey_plan_items_org_journey_live (INDEX)
CREATE INDEX idx_journey_plan_items_org_journey_live ON journeys.journey_plan_items USING btree (organization_id, journey_id) WHERE (deleted_at IS NULL);

-- idx_journeys_audit_log_org_entity (INDEX)
CREATE INDEX idx_journeys_audit_log_org_entity ON journeys.audit_log USING btree (organization_id, entity_type, entity_id, recorded_at);

-- idx_journeys_conflict_org_entity (INDEX)
CREATE INDEX idx_journeys_conflict_org_entity ON journeys.sync_conflict_log USING btree (organization_id, entity_type, entity_id);

-- idx_journeys_org_status_live (INDEX)
CREATE INDEX idx_journeys_org_status_live ON journeys.journeys USING btree (organization_id, status, created_at DESC) WHERE (deleted_at IS NULL);

-- uq_journey_plan_items_journey_apiary_live (INDEX)
CREATE UNIQUE INDEX uq_journey_plan_items_journey_apiary_live ON journeys.journey_plan_items USING btree (journey_id, apiary_id) WHERE (deleted_at IS NULL);

-- journey_plan_items journey_plan_items_journey_id_fkey (FK CONSTRAINT)
ALTER TABLE ONLY journeys.journey_plan_items
    ADD CONSTRAINT journey_plan_items_journey_id_fkey FOREIGN KEY (journey_id) REFERENCES journeys.journeys(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--
