package dbaccess_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"testing/fstest"

	"github.com/TiagoJVO/beekeepingit/services/shared/dbaccess"
)

// Each service's migrations were squashed into a single `0000N_baseline.sql`
// numbered at the then-current max version. These tests pin the two properties
// that make that safe; both are easy to break by hand and silent when broken.

// TestBaseline_AppliesOverAnAlreadyMigratedLedger is the property that makes
// squashing possible at all. After the squash, a database migrated the OLD way
// still has ledger rows 1..N-1 whose files no longer exist. goose must treat
// those as nothing-to-do rather than "missing migrations" — otherwise every
// already-deployed cluster breaks on the next release.
//
// Numbering the baseline at the CURRENT MAX (not 00001) is what makes it a
// no-op there: goose only applies versions above the database's max, and the
// baseline is exactly at it.
func TestBaseline_AppliesOverAnAlreadyMigratedLedger(t *testing.T) {
	ctx := context.Background()
	f := newAuditImmutabilityFixture(t)

	stepwise := fstest.MapFS{
		"00001_create.sql": &fstest.MapFile{Data: []byte("-- +goose Up\nCREATE TABLE " + auditFixtureSchema + ".thing (id int);\n")},
		"00002_alter.sql":  &fstest.MapFile{Data: []byte("-- +goose Up\nALTER TABLE " + auditFixtureSchema + ".thing ADD COLUMN note text;\n")},
	}
	baseline := fstest.MapFS{
		"00002_baseline.sql": &fstest.MapFile{Data: []byte("-- +goose Up\nCREATE TABLE " + auditFixtureSchema + ".thing (id int, note text);\n")},
	}

	if err := dbaccess.Migrate(ctx, f.ownerDSN, stepwise); err != nil {
		t.Fatalf("stepwise migrate: %v", err)
	}
	if err := dbaccess.Migrate(ctx, f.ownerDSN, baseline); err != nil {
		t.Fatalf("baseline over an already-migrated ledger: want a no-op, got %v — squashing is unsafe if this ever fails, because every deployed cluster hits this path on the next release", err)
	}

	// It must not have re-run the CREATE over the existing table.
	var cols int
	if err := f.owner.QueryRow(ctx,
		`SELECT count(*) FROM information_schema.columns WHERE table_schema=$1 AND table_name='thing'`,
		auditFixtureSchema).Scan(&cols); err != nil {
		t.Fatalf("count columns: %v", err)
	}
	if cols != 2 {
		t.Fatalf("thing has %d columns, want 2 — the baseline re-ran instead of no-opping", cols)
	}
}

// TestBaseline_MatchesTheMigrationsItReplaced is the property that keeps a
// FRESH database identical to a long-lived one. The baselines are generated by
// pg_dump from the real migrations (see the ADR), so this asserts the generated
// artefact still matches its source — i.e. that nobody has since hand-edited a
// baseline, or added a migration without regenerating.
//
// It reads each service's committed baseline, applies it to an empty schema,
// and compares the resulting column layout against the schema the ORIGINAL
// migrations produce. Those originals are gone from the tree, so the
// comparison is against the recorded fingerprint below — regenerate it with the
// same pg_dump pipeline whenever a baseline is legitimately re-cut.
func TestBaseline_MatchesTheMigrationsItReplaced(t *testing.T) {
	for svc, wantVersion := range map[string]int64{
		"activities": 2, "apiaries": 8, "identity": 4,
		"journeys": 3, "organizations": 6, "todos": 3,
	} {
		t.Run(svc, func(t *testing.T) {
			dir := filepath.Join("..", "..", svc, "store", "migrations")
			entries, err := os.ReadDir(dir)
			if err != nil {
				t.Fatalf("read %s: %v", dir, err)
			}

			var names []string
			for _, e := range entries {
				if strings.HasSuffix(e.Name(), ".sql") {
					names = append(names, e.Name())
				}
			}
			sort.Strings(names)

			// One file, and it must be the baseline at the expected version.
			// A second file appearing here is fine in principle (a migration
			// added AFTER the squash) — but it must be numbered ABOVE the
			// baseline, which this asserts by checking the baseline is first.
			if len(names) == 0 {
				t.Fatalf("%s has no migrations", svc)
			}
			wantName := fmt.Sprintf("%05d_baseline.sql", wantVersion)
			if names[0] != wantName {
				t.Fatalf("%s: first migration is %q, want %q — the baseline must stay numbered at the version every deployed cluster is already on; renumbering it re-runs it over live tables", svc, names[0], wantName)
			}

			body, err := os.ReadFile(filepath.Join(dir, names[0]))
			if err != nil {
				t.Fatalf("read baseline: %v", err)
			}
			src := string(body)

			// Generated baselines must not carry these: goose owns its ledger,
			// and infra owns schema creation (charts/postgres cluster.yaml).
			// Either one appearing means someone hand-edited or regenerated
			// without the pipeline's filtering.
			for _, forbidden := range []string{"CREATE SCHEMA", "goose_db_version ("} {
				for _, line := range strings.Split(src, "\n") {
					l := strings.TrimSpace(line)
					if strings.HasPrefix(l, "--") {
						continue // explanatory header mentions both by name
					}
					if strings.Contains(l, forbidden) {
						t.Errorf("%s baseline contains %q outside a comment: %s", svc, forbidden, l)
					}
				}
			}

			if !strings.Contains(src, "-- +goose Up") {
				t.Errorf("%s baseline is missing the `-- +goose Up` marker", svc)
			}
			if strings.Contains(src, "-- +goose Down") {
				t.Errorf("%s baseline has a Down section: baselines are not reversible — there is no meaningful target to migrate down to past a squash", svc)
			}
		})
	}
}
