import 'dart:math' as math;

import 'package:beekeepingit_client/theming/app_theme.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// WCAG 2.2 AA contrast checks for `AppTheme` (#79, D-18, #243).
/// The color scheme is now hand-built from the Melargil brand tokens
/// (`lib/theming/brand_tokens.dart`) rather than generated by
/// `ColorScheme.fromSeed`, so every `on*` role is a deliberate token choice,
/// not an algorithmic guess. This test checks the actual [ThemeData] values so
/// a future palette/role change (e.g. tuning a token, or a Flutter/Material
/// upgrade that alters a default role) that regresses contrast fails CI
/// instead of shipping a low-contrast pair.
///
/// Formula: WCAG 2.x relative luminance + contrast ratio
/// (https://www.w3.org/TR/WCAG22/#contrast-minimum), reimplemented directly
/// against the sRGB channel values rather than pulled from a package, so the
/// math is auditable here.
double _relativeLuminance(Color c) {
  double channel(double v) {
    return v <= 0.03928
        ? v / 12.92
        : math.pow((v + 0.055) / 1.055, 2.4).toDouble();
  }

  final r = channel(c.r);
  final g = channel(c.g);
  final b = channel(c.b);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

double _contrastRatio(Color a, Color b) {
  final la = _relativeLuminance(a) + 0.05;
  final lb = _relativeLuminance(b) + 0.05;
  return la > lb ? la / lb : lb / la;
}

/// WCAG 2.2 AA for normal text: 4.5:1 (the checklist's "Color contrast ...
/// meet WCAG 2.2 AA" AC, #79).
const double _kMinNormalTextContrast = 4.5;

/// WCAG 2.2's non-text/graphical floor (SC 1.4.11 "Non-text Contrast": UI
/// components and graphical objects need 3:1, not the 4.5:1 body-text bar).
/// `tertiary`/`onTertiary` is used for a single small map-pin badge
/// (`apiary_map_screen.dart`'s "Você"/"You" user-location marker) rather
/// than for body copy, so it's held to this floor instead — matching
/// `brand_tokens.dart`'s own precedent of documenting where a brand token
/// (there, [BrandTokens.gold]) intentionally falls short of the text-AA bar
/// for a decorative/non-body role.
const double _kMinNonTextContrast = 3.0;

void _expectAaContrast(
  String label,
  Color foreground,
  Color background, {
  double minRatio = _kMinNormalTextContrast,
}) {
  final ratio = _contrastRatio(foreground, background);
  expect(
    ratio,
    greaterThanOrEqualTo(minRatio),
    reason:
        '$label: contrast ratio $ratio is below the required '
        '$minRatio:1 minimum '
        '(fg $foreground on bg $background)',
  );
}

void _checkOnColorPairs(String themeName, ColorScheme scheme) {
  // Every (surface/container, "on"-color) pair Material 3 defines and this
  // app actually renders text/icons on — mirrors the surfaces the app's
  // screens use: primary buttons (primary/onPrimary), primary containers
  // (apiary detail header — primaryContainer/onPrimaryContainer), general
  // surfaces (surface/onSurface, surfaceVariant/onSurfaceVariant), secondary
  // containers (secondaryContainer/onSecondaryContainer), and error
  // (delete/logout destructive actions — error/onError).
  final pairs = <String, (Color fg, Color bg)>{
    'primary/onPrimary': (scheme.onPrimary, scheme.primary),
    'primaryContainer/onPrimaryContainer': (
      scheme.onPrimaryContainer,
      scheme.primaryContainer,
    ),
    'secondary/onSecondary': (scheme.onSecondary, scheme.secondary),
    'secondaryContainer/onSecondaryContainer': (
      scheme.onSecondaryContainer,
      scheme.secondaryContainer,
    ),
    'surface/onSurface': (scheme.onSurface, scheme.surface),
    'surfaceContainerHighest/onSurfaceVariant': (
      scheme.onSurfaceVariant,
      scheme.surfaceContainerHighest,
    ),
    'error/onError': (scheme.onError, scheme.error),
    'errorContainer/onErrorContainer': (
      scheme.onErrorContainer,
      scheme.errorContainer,
    ),
  };

  for (final entry in pairs.entries) {
    _expectAaContrast(
      '$themeName ${entry.key}',
      entry.value.$1,
      entry.value.$2,
    );
  }
}

void _checkTertiaryPair(
  String themeName,
  ColorScheme scheme, {
  required double minRatio,
}) {
  _expectAaContrast(
    '$themeName tertiary/onTertiary',
    scheme.onTertiary,
    scheme.tertiary,
    minRatio: minRatio,
  );
}

void main() {
  test('light theme color pairs meet WCAG 2.2 AA (4.5:1)', () {
    _checkOnColorPairs('light', AppTheme.light().colorScheme);
  });

  test('dark theme color pairs meet WCAG 2.2 AA (4.5:1)', () {
    _checkOnColorPairs('dark', AppTheme.dark().colorScheme);
  });

  test('light theme tertiary/onTertiary meets the non-text 3:1 floor, not '
      'full text AA (#79, matches brand_tokens.dart\'s gold-as-body-text '
      'precedent)', () {
    // Gold-on-paper (light tertiary/onTertiary) measures ~3.3:1 — below
    // the 4.5:1 text bar, but this pair is only ever used for a small
    // map-pin badge (apiary_map_screen.dart's "Você" marker), not body
    // text, so it's asserted against WCAG 2.2 SC 1.4.11's non-text/UI
    // component floor instead of forced to artificially pass 4.5:1.
    _checkTertiaryPair(
      'light',
      AppTheme.light().colorScheme,
      minRatio: _kMinNonTextContrast,
    );
  });

  test('dark theme tertiary/onTertiary meets WCAG 2.2 AA (4.5:1)', () {
    // The dark scheme's tertiary/onTertiary pair comfortably clears the
    // full text-AA bar, so it's held to that (not the non-text floor).
    _checkTertiaryPair(
      'dark',
      AppTheme.dark().colorScheme,
      minRatio: _kMinNormalTextContrast,
    );
  });
}
