import 'dart:math' as math;

import 'package:beekeepingit_client/theming/app_theme.dart';
import 'package:beekeepingit_client/theming/brand_theme.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// WCAG 2.2 AA contrast checks for `AppTheme` (#79, D-18, #243).
/// The color scheme is now hand-built from the Melargil brand tokens
/// (`lib/theming/brand_tokens.dart`) rather than generated by
/// `ColorScheme.fromSeed`, so every `on*` role is a deliberate token choice,
/// not an algorithmic guess. This test checks the actual [ThemeData] values so
/// a future palette/role change (e.g. tuning a token, or a Flutter/Material
/// upgrade that alters a default role) that regresses contrast fails CI
/// instead of shipping a low-contrast pair.
///
/// Formula: WCAG 2.x relative luminance + contrast ratio
/// (https://www.w3.org/TR/WCAG22/#contrast-minimum), reimplemented directly
/// against the sRGB channel values rather than pulled from a package, so the
/// math is auditable here.
double _relativeLuminance(Color c) {
  double channel(double v) {
    return v <= 0.03928
        ? v / 12.92
        : math.pow((v + 0.055) / 1.055, 2.4).toDouble();
  }

  final r = channel(c.r);
  final g = channel(c.g);
  final b = channel(c.b);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

double _contrastRatio(Color a, Color b) {
  final la = _relativeLuminance(a) + 0.05;
  final lb = _relativeLuminance(b) + 0.05;
  return la > lb ? la / lb : lb / la;
}

/// WCAG 2.2 AA for normal text: 4.5:1 (the checklist's "Color contrast ...
/// meet WCAG 2.2 AA" AC, #79).
const double _kMinNormalTextContrast = 4.5;

/// WCAG 2.2's non-text/graphical floor (SC 1.4.11 "Non-text Contrast": UI
/// components and graphical objects need 3:1, not the 4.5:1 body-text bar).
/// `tertiary`/`onTertiary` is used for a single small map-pin badge
/// (`apiary_map_screen.dart`'s "Você"/"You" user-location marker) rather
/// than for body copy, so it's held to this floor instead — matching
/// `brand_tokens.dart`'s own precedent of documenting where a brand token
/// (there, [BrandTokens.gold]) intentionally falls short of the text-AA bar
/// for a decorative/non-body role.
const double _kMinNonTextContrast = 3.0;

/// A comfortable margin above the 4.5:1 AA floor (WCAG 2.2 AAA for normal
/// text, 7:1). The `surfaceContainerHighest`/`onSurfaceVariant` pair carries
/// the journey counter/badge text (`journeys_list_screen.dart`'s
/// `_ProgressBadge`/`_StatusBadge`, `journey_detail_screen.dart`'s
/// `_VisitedBadge`, `journey_stats_detail_screen.dart`'s `_VisitBadge`). In
/// light mode it previously sat at only ~4.64:1 — passing the floor but
/// rendering as barely-legible in the field (#423). This bar guards that pair
/// (both brightnesses) so a future token nudge can't silently drop it back to
/// marginal.
const double _kComfortableTextContrast = 7.0;

void _expectAaContrast(
  String label,
  Color foreground,
  Color background, {
  double minRatio = _kMinNormalTextContrast,
}) {
  final ratio = _contrastRatio(foreground, background);
  expect(
    ratio,
    greaterThanOrEqualTo(minRatio),
    reason:
        '$label: contrast ratio $ratio is below the required '
        '$minRatio:1 minimum '
        '(fg $foreground on bg $background)',
  );
}

void _checkOnColorPairs(String themeName, ColorScheme scheme) {
  // Every (surface/container, "on"-color) pair Material 3 defines and this
  // app actually renders text/icons on — mirrors the surfaces the app's
  // screens use: primary buttons (primary/onPrimary), primary containers
  // (apiary detail header — primaryContainer/onPrimaryContainer), general
  // surfaces (surface/onSurface, surfaceVariant/onSurfaceVariant), secondary
  // containers (secondaryContainer/onSecondaryContainer), and error
  // (delete/logout destructive actions — error/onError).
  final pairs = <String, (Color fg, Color bg)>{
    'primary/onPrimary': (scheme.onPrimary, scheme.primary),
    'primaryContainer/onPrimaryContainer': (
      scheme.onPrimaryContainer,
      scheme.primaryContainer,
    ),
    'secondary/onSecondary': (scheme.onSecondary, scheme.secondary),
    'secondaryContainer/onSecondaryContainer': (
      scheme.onSecondaryContainer,
      scheme.secondaryContainer,
    ),
    'surface/onSurface': (scheme.onSurface, scheme.surface),
    // NOTE: surfaceContainerHighest/onSurfaceVariant (the counter/badge text
    // pair) is intentionally NOT here — it's held to the higher
    // _kComfortableTextContrast bar via _checkBadgeTextPair below, not this
    // 4.5:1 floor.
    'error/onError': (scheme.onError, scheme.error),
    'errorContainer/onErrorContainer': (
      scheme.onErrorContainer,
      scheme.errorContainer,
    ),
  };

  for (final entry in pairs.entries) {
    _expectAaContrast(
      '$themeName ${entry.key}',
      entry.value.$1,
      entry.value.$2,
    );
  }
}

/// Guards the counter/badge text pair
/// (`surfaceContainerHighest`/`onSurfaceVariant`) against the comfortable
/// ≥7:1 margin rather than the bare 4.5:1 floor (#423).
void _checkBadgeTextPair(String themeName, ColorScheme scheme) {
  _expectAaContrast(
    '$themeName surfaceContainerHighest/onSurfaceVariant (counter/badge text)',
    scheme.onSurfaceVariant,
    scheme.surfaceContainerHighest,
    minRatio: _kComfortableTextContrast,
  );
}

/// The two roles an **outlined** control is made of, each checked against the
/// ground it sits on (`surface`): its label/icon draws `primary` and its
/// border draws `outline` (Material 3's `OutlinedButton` defaults). Neither
/// pair was in the list above, which is how light mode ended up rendering
/// secondary buttons as honey-on-cream at ~1.84:1 (#627) — honey is a *fill*
/// color (it pairs with the dark `onHoney` ink), never a foreground on a light
/// ground. Asserting them here applies `brand_tokens.dart`'s own "AppTheme
/// picks a different token for that role" rule to the roles Material sprays
/// across every accent icon, link-style label and outlined control.
///
/// The label is text, so it takes the 4.5:1 bar; the border is a UI-component
/// boundary, so it takes SC 1.4.11's 3:1 non-text floor.
void _checkOutlinedControlRoles(String themeName, ColorScheme scheme) {
  _expectAaContrast(
    '$themeName surface/primary (outlined control label + accent icons)',
    scheme.primary,
    scheme.surface,
  );
  _expectAaContrast(
    '$themeName surface/outline (control borders: buttons, inputs, chips)',
    scheme.outline,
    scheme.surface,
    minRatio: _kMinNonTextContrast,
  );
}

/// A focused field's border must clear the same 3:1 boundary floor **and**
/// stay at least as strong as the resting border it replaces — a focus ring
/// that is dimmer than the unfocused state reads as losing focus, not gaining
/// it. `AppTheme`'s `inputDecorationTheme` draws the resting border from
/// `outline` and the focus ring from a brighter role per brightness.
void _checkFocusRing(String themeName, ThemeData theme) {
  final scheme = theme.colorScheme;
  final focused =
      theme.inputDecorationTheme.focusedBorder! as OutlineInputBorder;
  final enabled =
      theme.inputDecorationTheme.enabledBorder! as OutlineInputBorder;
  _expectAaContrast(
    '$themeName focused field border',
    focused.borderSide.color,
    scheme.surface,
    minRatio: _kMinNonTextContrast,
  );
  final focusRatio = _contrastRatio(focused.borderSide.color, scheme.surface);
  final restRatio = _contrastRatio(enabled.borderSide.color, scheme.surface);
  expect(
    focusRatio,
    greaterThanOrEqualTo(restRatio),
    reason:
        '$themeName: the focus ring ($focusRatio:1) must not be dimmer than '
        'the resting border it replaces ($restRatio:1)',
  );
}

/// The colors the **secondary action button** actually resolves to — the
/// `outlinedButtonTheme` foreground/side the theme ships, not just the raw
/// scheme roles — measured against the surface it is drawn on. This is the
/// pair #627 reported: it must read as outlined plum, never honey-on-cream.
void _checkSecondaryButtonStyle(String themeName, ThemeData theme) {
  final style = theme.outlinedButtonTheme.style;
  final scheme = theme.colorScheme;
  final foreground = style?.foregroundColor?.resolve(<WidgetState>{});
  final side = style?.side?.resolve(<WidgetState>{});
  expect(
    foreground,
    isNotNull,
    reason:
        '$themeName: outlinedButtonTheme must pin the secondary action\'s '
        'foreground rather than inheriting whatever `primary` happens to be',
  );
  expect(
    side,
    isNotNull,
    reason: '$themeName: the secondary action button needs a visible border',
  );
  _expectAaContrast(
    '$themeName secondary button label',
    foreground!,
    scheme.surface,
  );
  _expectAaContrast(
    '$themeName secondary button border',
    side!.color,
    scheme.surface,
    minRatio: _kMinNonTextContrast,
  );
}

void _checkTertiaryPair(
  String themeName,
  ColorScheme scheme, {
  required double minRatio,
}) {
  _expectAaContrast(
    '$themeName tertiary/onTertiary',
    scheme.onTertiary,
    scheme.tertiary,
    minRatio: minRatio,
  );
}

void main() {
  test('light theme color pairs meet WCAG 2.2 AA (4.5:1)', () {
    _checkOnColorPairs('light', AppTheme.light().colorScheme);
  });

  test('dark theme color pairs meet WCAG 2.2 AA (4.5:1)', () {
    _checkOnColorPairs('dark', AppTheme.dark().colorScheme);
  });

  test('counter/badge text pair clears the comfortable 7:1 margin, not just '
      'the 4.5:1 floor, in both brightnesses (#423)', () {
    // surfaceContainerHighest/onSurfaceVariant carries the journey
    // counter/badge text. Light mode sat at only ~4.64:1 (barely-legible in
    // the field); darkening the `muted` token lifts it to ~7.10:1. Dark mode
    // already sits at ~7.87:1. Both are asserted against the higher bar so a
    // future nudge can't silently drop this pair back to marginal.
    _checkBadgeTextPair('light', AppTheme.light().colorScheme);
    _checkBadgeTextPair('dark', AppTheme.dark().colorScheme);
  });

  test('light theme tertiary/onTertiary meets the non-text 3:1 floor, not '
      'full text AA (#79, matches brand_tokens.dart\'s gold-as-body-text '
      'precedent)', () {
    // Gold-on-paper (light tertiary/onTertiary) measures ~3.3:1 — below
    // the 4.5:1 text bar, but this pair is only ever used for a small
    // map-pin badge (apiary_map_screen.dart's "Você" marker), not body
    // text, so it's asserted against WCAG 2.2 SC 1.4.11's non-text/UI
    // component floor instead of forced to artificially pass 4.5:1.
    _checkTertiaryPair(
      'light',
      AppTheme.light().colorScheme,
      minRatio: _kMinNonTextContrast,
    );
  });

  test('dark theme tertiary/onTertiary meets WCAG 2.2 AA (4.5:1)', () {
    // The dark scheme's tertiary/onTertiary pair comfortably clears the
    // full text-AA bar, so it's held to that (not the non-text floor).
    _checkTertiaryPair(
      'dark',
      AppTheme.dark().colorScheme,
      minRatio: _kMinNormalTextContrast,
    );
  });

  test('outlined-control roles (surface/primary, surface/outline) are legible '
      'on the surface in both brightnesses (#627)', () {
    // An outlined secondary button's label draws `primary` and its border
    // draws `outline`. In light mode `primary` was honey — 1.84:1 on cream —
    // so the label was effectively invisible in the sunlight the field app is
    // used in, and `outline` (the prototype's #D8D1C0 hairline) sat at 1.37:1,
    // below SC 1.4.11's 3:1 floor for a control boundary.
    _checkOutlinedControlRoles('light', AppTheme.light().colorScheme);
    _checkOutlinedControlRoles('dark', AppTheme.dark().colorScheme);
  });

  test('the secondary action button resolves to outlined plum, legible on the '
      'surface in both brightnesses (#627)', () {
    // Honey is reserved for the single primary action per screen
    // (docs/design/prototype.md: "Honey is the only primary action. Secondary
    // = outlined plum."), so the secondary button pins its own foreground
    // instead of inheriting whichever role Material's defaults reach for.
    _checkSecondaryButtonStyle('light', AppTheme.light());
    _checkSecondaryButtonStyle('dark', AppTheme.dark());
  });

  test('a focused field border clears the 3:1 boundary floor and is never '
      'dimmer than the resting border (#627)', () {
    // Lifting the dark `outline` to plum 500 without touching the focus ring
    // would have inverted the two in dark mode: focusing a field would have
    // made its border dimmer (2.06:1) than when unfocused (3.51:1).
    _checkFocusRing('light', AppTheme.light());
    _checkFocusRing('dark', AppTheme.dark());
  });

  // --- BrandTheme extension roles (hero surface, notes callout, activity-type
  // tints) — the look-and-feel roles Material's ColorScheme has no slot for
  // (lib/theming/brand_theme.dart). These carry real text/graphics on the
  // restyled screens, so they get the same computational AA guard the
  // ColorScheme roles above already have.

  test('BrandTheme text-carrying roles meet WCAG 2.2 AA (4.5:1) in both '
      'brightnesses', () {
    for (final (name, brand) in <(String, BrandTheme)>[
      ('light', AppTheme.light().extension<BrandTheme>()!),
      ('dark', AppTheme.dark().extension<BrandTheme>()!),
    ]) {
      // Hero title + body (apiary/activity detail plum header) and the notes
      // "sticky note" callout are genuine body text, held to the 4.5:1 bar.
      _expectAaContrast(
        '$name hero onHeroSurface',
        brand.onHeroSurface,
        brand.heroSurface,
      );
      _expectAaContrast(
        '$name hero onHeroSurfaceMuted',
        brand.onHeroSurfaceMuted,
        brand.heroSurface,
      );
      _expectAaContrast('$name notes text', brand.notesText, brand.notesBg);
    }
  });

  test('BrandTheme activity-type icon tints meet the non-text 3:1 floor '
      '(graphical), except the decorative gold cresta pair', () {
    // The type icon tiles are graphical objects; in light mode their tints are
    // opaque so contrast is meaningful (dark-mode tints are translucent washes
    // over the plum card, so a raw-token ratio would be misleading and is not
    // asserted here). feeding/treatment/generic clear the 3:1 non-text floor.
    final brand = AppTheme.light().extension<BrandTheme>()!;
    for (final (name, v) in <(String, ActivityTypeVisual)>[
      ('feeding', brand.feeding),
      ('treatment', brand.treatment),
      ('generic', brand.generic),
    ]) {
      _expectAaContrast(
        'light activity $name icon-on-tint',
        v.color,
        v.tint,
        minRatio: _kMinNonTextContrast,
      );
    }
    // Cresta is honey/gold-on-sand (~2.85:1), below even the 3:1 non-text
    // floor — the same documented gold-as-decorative exception brand_tokens
    // and the tertiary pair above already call out. It's exempt from SC
    // 1.4.11 because the icon is DECORATIVE: the activity type is always
    // shown as an adjacent text label (and the apiary/hive name carries the
    // row's meaning), so the tinted icon never solely conveys content. Guard
    // only that it hasn't regressed to invisibly-low contrast.
    final cresta = _contrastRatio(brand.cresta.color, brand.cresta.tint);
    expect(
      cresta,
      greaterThan(1.3),
      reason:
          'cresta icon-on-tint ($cresta:1) — decorative, but should stay '
          'visibly distinct from its tile',
    );
  });
}
