-- +goose Up
-- BASELINE for the `organizations` schema — the squashed equivalent of migrations
-- 00001..00006, generated by pg_dump from those migrations rather than written
-- by hand (a hand-written baseline is precisely how a fresh database and an
-- already-migrated one drift apart).
--
-- WHY IT IS NUMBERED 00006 AND NOT 00001. goose applies any version above the
-- database's current max. Numbering the baseline at the CURRENT MAX means an
-- already-migrated cluster (staging is at 6) sees nothing to do, while a
-- fresh database applies this one file and lands on the SAME version number.
-- Both end up with identical schema AND identical ledger state. Numbering it
-- 00001 would instead leave fresh and existing clusters on different versions
-- forever.
--
-- CONSEQUENCE: this baseline may only ever be re-cut when every live
-- environment is at or above its version. Squashing below a deployed cluster's
-- version would make goose try to apply it over tables that already exist.
-- Verified before this was generated: staging was at exactly 00006.
--
-- The `goose_db_version` ledger is deliberately absent (goose creates it), as is
-- CREATE SCHEMA (infra owns schemas — charts/postgres/templates/cluster.yaml).
--
-- There is no Down. Baselines are not reversible: down-migrating past a squash
-- has no meaningful target, and the pre-squash steps no longer exist to unwind.

-- audit_log (TABLE)
CREATE TABLE organizations.audit_log (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    entity_type text NOT NULL,
    entity_id uuid NOT NULL,
    change_type text NOT NULL,
    actor_user_id uuid,
    occurred_at timestamp with time zone NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    changed_fields text[],
    change jsonb NOT NULL,
    actor_scope text DEFAULT 'member'::text NOT NULL,
    CONSTRAINT audit_log_actor_scope_check CHECK ((actor_scope = ANY (ARRAY['member'::text, 'platform_operator'::text]))),
    CONSTRAINT audit_log_change_type_check CHECK ((change_type = ANY (ARRAY['create'::text, 'update'::text, 'delete'::text]))),
    CONSTRAINT audit_log_entity_type_check CHECK ((entity_type = ANY (ARRAY['organization'::text, 'membership'::text, 'invitation'::text])))
);

-- invitations (TABLE)
CREATE TABLE organizations.invitations (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    email text NOT NULL,
    role text DEFAULT 'user'::text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    invited_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT invitations_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'user'::text]))),
    CONSTRAINT invitations_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'expired'::text, 'revoked'::text])))
);

-- memberships (TABLE)
CREATE TABLE organizations.memberships (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role text DEFAULT 'user'::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT memberships_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'user'::text]))),
    CONSTRAINT memberships_status_check CHECK ((status = ANY (ARRAY['active'::text, 'invited'::text, 'removed'::text])))
);

-- organizations (TABLE)
CREATE TABLE organizations.organizations (
    id uuid NOT NULL,
    name text NOT NULL,
    address text DEFAULT ''::text NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- audit_log audit_log_pkey (CONSTRAINT)
ALTER TABLE ONLY organizations.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);

-- invitations invitations_pkey (CONSTRAINT)
ALTER TABLE ONLY organizations.invitations
    ADD CONSTRAINT invitations_pkey PRIMARY KEY (id);

-- memberships memberships_organization_id_user_id_key (CONSTRAINT)
ALTER TABLE ONLY organizations.memberships
    ADD CONSTRAINT memberships_organization_id_user_id_key UNIQUE (organization_id, user_id);

-- memberships memberships_pkey (CONSTRAINT)
ALTER TABLE ONLY organizations.memberships
    ADD CONSTRAINT memberships_pkey PRIMARY KEY (id);

-- organizations organizations_pkey (CONSTRAINT)
ALTER TABLE ONLY organizations.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);

-- idx_audit_log_org_entity (INDEX)
CREATE INDEX idx_audit_log_org_entity ON organizations.audit_log USING btree (organization_id, entity_type, entity_id, recorded_at);

-- idx_invitations_email_pending (INDEX)
CREATE INDEX idx_invitations_email_pending ON organizations.invitations USING btree (lower(email)) WHERE (status = 'pending'::text);

-- idx_invitations_org_email_pending (INDEX)
CREATE UNIQUE INDEX idx_invitations_org_email_pending ON organizations.invitations USING btree (organization_id, lower(email)) WHERE (status = 'pending'::text);

-- idx_memberships_one_active_per_user (INDEX)
CREATE UNIQUE INDEX idx_memberships_one_active_per_user ON organizations.memberships USING btree (user_id) WHERE (status = 'active'::text);

-- idx_memberships_user_active (INDEX)
CREATE INDEX idx_memberships_user_active ON organizations.memberships USING btree (user_id) WHERE (status = 'active'::text);

-- idx_memberships_user_id (INDEX)
CREATE INDEX idx_memberships_user_id ON organizations.memberships USING btree (user_id);

-- invitations invitations_organization_id_fkey (FK CONSTRAINT)
ALTER TABLE ONLY organizations.invitations
    ADD CONSTRAINT invitations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations.organizations(id);

-- memberships memberships_organization_id_fkey (FK CONSTRAINT)
ALTER TABLE ONLY organizations.memberships
    ADD CONSTRAINT memberships_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations.organizations(id);


--
-- PostgreSQL database dump complete
--
