-- +goose Up
-- BASELINE for the `todos` schema — the squashed equivalent of migrations
-- 00001..00003, generated by pg_dump from those migrations rather than written
-- by hand (a hand-written baseline is precisely how a fresh database and an
-- already-migrated one drift apart).
--
-- WHY IT IS NUMBERED 00003 AND NOT 00001. goose applies any version above the
-- database's current max. Numbering the baseline at the CURRENT MAX means an
-- already-migrated cluster (staging is at 3) sees nothing to do, while a
-- fresh database applies this one file and lands on the SAME version number.
-- Both end up with identical schema AND identical ledger state. Numbering it
-- 00001 would instead leave fresh and existing clusters on different versions
-- forever.
--
-- CONSEQUENCE: this baseline may only ever be re-cut when every live
-- environment is at or above its version. Squashing below a deployed cluster's
-- version would make goose try to apply it over tables that already exist.
-- Verified before this was generated: staging was at exactly 00003.
--
-- The `goose_db_version` ledger is deliberately absent (goose creates it), as is
-- CREATE SCHEMA (infra owns schemas — charts/postgres/templates/cluster.yaml).
--
-- There is no Down. Baselines are not reversible: down-migrating past a squash
-- has no meaningful target, and the pre-squash steps no longer exist to unwind.

-- audit_log (TABLE)
CREATE TABLE todos.audit_log (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    entity_type text NOT NULL,
    entity_id uuid NOT NULL,
    change_type text NOT NULL,
    actor_user_id uuid,
    occurred_at timestamp with time zone NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    changed_fields text[],
    change jsonb NOT NULL,
    CONSTRAINT audit_log_change_type_check CHECK ((change_type = ANY (ARRAY['create'::text, 'update'::text, 'delete'::text])))
);

-- sync_conflict_log (TABLE)
CREATE TABLE todos.sync_conflict_log (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    entity_type text NOT NULL,
    entity_id uuid NOT NULL,
    winning_payload jsonb NOT NULL,
    losing_payload jsonb NOT NULL,
    winner text NOT NULL,
    actor_user_id uuid,
    occurred_at timestamp with time zone,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT sync_conflict_log_winner_check CHECK ((winner = ANY (ARRAY['server'::text, 'client'::text])))
);

-- todos (TABLE)
CREATE TABLE todos.todos (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    title text NOT NULL,
    description text,
    due_date date,
    priority text NOT NULL,
    status text DEFAULT 'open'::text NOT NULL,
    completed_at timestamp with time zone,
    assignee_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    apiary_id uuid
);

-- audit_log audit_log_pkey (CONSTRAINT)
ALTER TABLE ONLY todos.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);

-- sync_conflict_log sync_conflict_log_pkey (CONSTRAINT)
ALTER TABLE ONLY todos.sync_conflict_log
    ADD CONSTRAINT sync_conflict_log_pkey PRIMARY KEY (id);

-- todos todos_pkey (CONSTRAINT)
ALTER TABLE ONLY todos.todos
    ADD CONSTRAINT todos_pkey PRIMARY KEY (id);

-- idx_todos_audit_log_org_entity (INDEX)
CREATE INDEX idx_todos_audit_log_org_entity ON todos.audit_log USING btree (organization_id, entity_type, entity_id, recorded_at);

-- idx_todos_conflict_org_entity (INDEX)
CREATE INDEX idx_todos_conflict_org_entity ON todos.sync_conflict_log USING btree (organization_id, entity_type, entity_id);

-- idx_todos_org_apiary (INDEX)
CREATE INDEX idx_todos_org_apiary ON todos.todos USING btree (organization_id, apiary_id) WHERE ((deleted_at IS NULL) AND (apiary_id IS NOT NULL));

-- idx_todos_org_assignee (INDEX)
CREATE INDEX idx_todos_org_assignee ON todos.todos USING btree (organization_id, assignee_id) WHERE ((deleted_at IS NULL) AND (assignee_id IS NOT NULL));

-- idx_todos_org_status_due (INDEX)
CREATE INDEX idx_todos_org_status_due ON todos.todos USING btree (organization_id, status, due_date) WHERE (deleted_at IS NULL);


--
-- PostgreSQL database dump complete
--
