-- +goose Up
-- BASELINE for the `apiaries` schema — the squashed equivalent of migrations
-- 00001..00008, generated by pg_dump from those migrations rather than written
-- by hand (a hand-written baseline is precisely how a fresh database and an
-- already-migrated one drift apart).
--
-- WHY IT IS NUMBERED 00008 AND NOT 00001. goose applies any version above the
-- database's current max. Numbering the baseline at the CURRENT MAX means an
-- already-migrated cluster (staging is at 8) sees nothing to do, while a
-- fresh database applies this one file and lands on the SAME version number.
-- Both end up with identical schema AND identical ledger state. Numbering it
-- 00001 would instead leave fresh and existing clusters on different versions
-- forever.
--
-- CONSEQUENCE: this baseline may only ever be re-cut when every live
-- environment is at or above its version. Squashing below a deployed cluster's
-- version would make goose try to apply it over tables that already exist.
-- Verified before this was generated: staging was at exactly 00008.
--
-- The `goose_db_version` ledger is deliberately absent (goose creates it), as is
-- CREATE SCHEMA (infra owns schemas — charts/postgres/templates/cluster.yaml).
--
-- There is no Down. Baselines are not reversible: down-migrating past a squash
-- has no meaningful target, and the pre-squash steps no longer exist to unwind.

-- apiaries (TABLE)
CREATE TABLE apiaries.apiaries (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    location public.geography(Point,4326) NOT NULL,
    notes text,
    place_label text,
    CONSTRAINT apiaries_notes_check CHECK (((notes IS NULL) OR (char_length(notes) <= 10000))),
    CONSTRAINT apiaries_place_label_check CHECK (((place_label IS NULL) OR (char_length(place_label) <= 200)))
);

-- apiary_counters (TABLE)
CREATE TABLE apiaries.apiary_counters (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    apiary_id uuid NOT NULL,
    counter_type text NOT NULL,
    value integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT apiary_counters_value_check CHECK ((value >= 0))
);

-- audit_log (TABLE)
CREATE TABLE apiaries.audit_log (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    entity_type text NOT NULL,
    entity_id uuid NOT NULL,
    change_type text NOT NULL,
    actor_user_id uuid,
    occurred_at timestamp with time zone NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    changed_fields text[],
    change jsonb NOT NULL,
    CONSTRAINT audit_log_change_type_check CHECK ((change_type = ANY (ARRAY['create'::text, 'update'::text, 'delete'::text])))
);

-- sync_conflict_log (TABLE)
CREATE TABLE apiaries.sync_conflict_log (
    id uuid NOT NULL,
    organization_id uuid NOT NULL,
    entity_type text NOT NULL,
    entity_id uuid NOT NULL,
    winning_payload jsonb NOT NULL,
    losing_payload jsonb NOT NULL,
    winner text NOT NULL,
    actor_user_id uuid,
    occurred_at timestamp with time zone,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT sync_conflict_log_winner_check CHECK ((winner = ANY (ARRAY['server'::text, 'client'::text])))
);

-- apiaries apiaries_pkey (CONSTRAINT)
ALTER TABLE ONLY apiaries.apiaries
    ADD CONSTRAINT apiaries_pkey PRIMARY KEY (id);

-- apiary_counters apiary_counters_pkey (CONSTRAINT)
ALTER TABLE ONLY apiaries.apiary_counters
    ADD CONSTRAINT apiary_counters_pkey PRIMARY KEY (id);

-- audit_log audit_log_pkey (CONSTRAINT)
ALTER TABLE ONLY apiaries.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);

-- sync_conflict_log sync_conflict_log_pkey (CONSTRAINT)
ALTER TABLE ONLY apiaries.sync_conflict_log
    ADD CONSTRAINT sync_conflict_log_pkey PRIMARY KEY (id);

-- apiary_counters uq_apiary_counters_org_apiary_type (CONSTRAINT)
ALTER TABLE ONLY apiaries.apiary_counters
    ADD CONSTRAINT uq_apiary_counters_org_apiary_type UNIQUE (organization_id, apiary_id, counter_type);

-- idx_apiaries_location (INDEX)
CREATE INDEX idx_apiaries_location ON apiaries.apiaries USING gist (location);

-- idx_apiaries_org_live (INDEX)
CREATE INDEX idx_apiaries_org_live ON apiaries.apiaries USING btree (organization_id, id) WHERE (deleted_at IS NULL);

-- idx_apiary_counters_org_apiary (INDEX)
CREATE INDEX idx_apiary_counters_org_apiary ON apiaries.apiary_counters USING btree (organization_id, apiary_id);

-- idx_audit_log_org_entity (INDEX)
CREATE INDEX idx_audit_log_org_entity ON apiaries.audit_log USING btree (organization_id, entity_type, entity_id, recorded_at);

-- idx_conflict_org_entity (INDEX)
CREATE INDEX idx_conflict_org_entity ON apiaries.sync_conflict_log USING btree (organization_id, entity_type, entity_id);

-- apiary_counters apiary_counters_apiary_id_fkey (FK CONSTRAINT)
ALTER TABLE ONLY apiaries.apiary_counters
    ADD CONSTRAINT apiary_counters_apiary_id_fkey FOREIGN KEY (apiary_id) REFERENCES apiaries.apiaries(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--
